---
- name: Prepare Ubuntu Linux server with debug tools
  hosts: gdb-box
  remote_user: root
  become: true
  gather_facts: false

  tasks:
    - name: Install required packages
      apt:
        update_cache: yes
        name:
          - python3
          - jq
          - gdb
          - nano
          - git
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present

    - name: Remove any previous docker related package
      apt:
        name:
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

